# Generated by Django 3.1.3 on 2020-12-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
