# Generated by Django 3.1.3 on 2020-12-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20201204_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cantidad',
            new_name='monto',
        ),
    ]
