# Generated by Django 3.1.3 on 2020-12-04 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_venta_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 4, 22, 15, 1, 761777), null=True),
        ),
    ]
